### PR TITLE
fix: Add configurable bad line handling to CsvToIon via OnBadLines enum

### LINKED ISSUE #80: Add handling for corrupted rows e.g. enum property `onBadLines` with options ERROR, WARN or SKIP to all `ToIon` plugins e.g. `CsvToIon`
### Feature description

in pandas, there is a ["on_bad_lines"](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) property:

```
on_bad_lines{‘error’, ‘warn’, ‘skip’}, default ‘error’
Specifies what to do upon encountering a bad line (a line with too many fields). Allowed values are :

'`error`', raise an Exception when a bad line is encountered.

'`warn`', raise a warning when a bad line is encountered and skip that line.

'`skip`', skip bad lines without raising or warning when they are encountered.
```

It's worth adding an enum property `onBadLines` with options ERROR, WARN or SKIP to all `ToIon` tasks to allow a more configurable handling of bad lines:

image

### PR DESCRIPTION
**Pull request by RedHolger**
closes #80 

What's Changed

Added a new OnBadLines enum with the following modes:

- ERROR → Throw an exception when encountering a malformed line (default).
- WARN → Log a warning and skip the bad line.
- SKIP → Silently skip bad lines without logging.

Integrated OnBadLines into the CsvToIon task:

- Handles both parsing errors (CsvParseException) and field count mismatches.
- Ensures consistent behavior across different error scenarios.

Added comprehensive unit tests:

- Validated behavior for ERROR, WARN, and SKIP modes.
- Covered malformed line scenarios, extra fields, and missing fields.

Refactored CSV processing logic for better clarity and extensibility.

### CODE REVIEW

**Comment by RedHolger** [comment]
@fdelbrayelle @Malaydewangan09 

**Error :** 

Test: io.kestra.plugin.serdes.avro.AvroConverterTest.rowWithMissingFieldsAndGoodSeparator
- File: src/test/java/io/kestra/plugin/serdes/avro/AvroConverterTest.java
- Line: 386
- Error Details: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "data" is null on cols with data [null] and schema ["int"] on field 'id' ...

Test: io.kestra.plugin.serdes.avro.AvroConverterTest.csvStrictSchemaArray
- File: src/test/java/io/kestra/plugin/serdes/avro/AvroConverterTest.java
- Line: 183

- Error Details:

     Expected: IllegalStrictRowConversion
     Actual: IllegalRowConvertion
     Message: The test fails with an AssertionError because the thrown exception’s message doesn’t match the expected string due    to the typo ("Convertion" instead of "Conversion").

Test: io.kestra.plugin.serdes.csv.CsvToIonWriterTest.noHeader
- File: src/test/java/io/kestra/plugin/serdes/csv/CsvToIonWriterTest.java
- Lines: 65 and 78
- Error Details:

     Expected: Ion output matching the CSV rows, e.g., a list of rows like ["119736", "FL", ...].
     Actual: "nnnnn" (likely 5 null values, suggesting the code misinterprets the CSV as empty or null fields).
     AssertionError: The test fails because the output string doesn’t match the expected row data.

These test cases are unrelated to above PR, do you want me to fix them?

**Comment by RedHolger** [comment]
Yes, I am currently dealing with some failing test cases for Avro conversion. The CSV conversion is complete, and I will create a combined pull request for both.

**Comment by RedHolger** [comment]
I've pushed my latest changes addressing bad line handling and Avro conversion improvements.

Currently, two tests are failing:

1. **`rowWithMissingFieldsAndGoodSeparator()`** fails due to a mismatch in expected error message:
   - Expected an error mentioning the `"double"` field with null data.
   - Actual error involves a null `"id"` (int) field causing a `NullPointerException`.

2. **`csvStrictSchemaArray()`** fails because of an inconsistent exception name:
   - Expected `"IllegalStrictRowConversion"`.
   - Actual: `"IllegalRowConvertion"` (typo in exception class name).

Please advise on how you'd like to proceed with these failing cases.

File: src/main/java/io/kestra/plugin/serdes/avro/AbstractAvroConverter.java [hunk 1]
```diff
@@ -129,6 +130,13 @@ public abstract class AbstractAvroConverter extends Task {
     )
     protected final Property<String> timeZoneId = Property.ofValue(ZoneId.systemDefault().toString());
 
+    @Builder.Default
+    @io.swagger.v3.oas.annotations.media.Schema(
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/serdes/avro/AbstractAvroConverter.java]: Import the class properly:

```suggestion
    @Schema(
```

File: src/main/java/io/kestra/plugin/serdes/avro/AvroConverter.java [hunk 2]
```diff
@@ -141,14 +172,30 @@ public GenericData.Record fromArray(Schema schema, List<String> data) throws Ill
...
-    protected Object convert(Schema schema, Object data) throws IllegalCellConversion {
+    protected Object convert(Schema schema, Object data, OnBadLines onBadLines, String fieldName) throws IllegalCellConversion {
+
+
+        /*if (data == null) {
+            if (schema.getType() != Schema.Type.NULL && !(schema.getType() == Schema.Type.UNION && schema.getTypes().stream().anyMatch(s -> s.getType() == Schema.Type.NULL))) {
+                throw new IllegalCellConversion(schema, null, new IllegalArgumentException("Null value for non-nullable field '" + fieldName + "'"));
+            }
+            return null;
+        }*/
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/serdes/avro/AvroConverter.java]: Don't push commented code 🙏

File: src/main/java/io/kestra/plugin/serdes/csv/CsvToIon.java [hunk 3]
```diff
@@ -149,8 +158,20 @@ public Output run(RunContext runContext) throws Exception {
             var headerValue = runContext.render(header).as(Boolean.class).orElseThrow();
             var skipRowsValue = runContext.render(this.skipRows).as(Integer.class).orElseThrow();
             Map<Integer, String> headers = new TreeMap<>();
+            OnBadLines onBadLinesValue = runContext.render(this.onBadLines).as(OnBadLines.class).orElse(OnBadLines.ERROR);
```
[the remark this answers is not in the document]
Comment (Malaydewangan09) [reply src/main/java/io/kestra/plugin/serdes/csv/CsvToIon.java]: yes @RedHolger

**Comment by RedHolger** [comment]
Yes, I’m done with the Avro fix. I’ll commit the fixes for it and then start working on JSON and Excel handling next.
